# Generated by Django 5.0.6 on 2024-06-17 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('carousel', models.ImageField(upload_to='carousel/images/')),
                ('status', models.CharField(choices=[('IN_STOCK', 'in_stock'), ('OUT_OF_STOCK', 'out_of_stock')], default='IN_STOCK', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('subcategory_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
