# Generated by Django 5.0.6 on 2024-06-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_options_purchase_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('CANCELED', 'cancelled'), ('PENDING', 'pending')], default='PENDING', max_length=255),
        ),
    ]
