# Generated by Django 5.0.6 on 2024-06-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('PENDING', 'pending'), ('CANCELED', 'cancelled')], default='PENDING', max_length=255),
        ),
    ]
