# Generated by Django 5.0.6 on 2024-06-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_purchase_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
